#!/usr/bin/env python3
"""Generate a LovyanGFX/Adafruit GFX font covering ASCII **and Latin-1**.

Why this exists: every font LovyanGFX ships stops at 0x7E or 0x7F. `Font2`
literally computes `(uniCode - 0x20) < 0x60` — 96 glyphs. So `á` renders as a
box, which for a project whose docs, packs and buddy all speak Spanish is not a
cosmetic problem. The only Unicode fonts in the library are efont, and those
are 17-32 MB of CJK.

Codepoints 0x20-0xFF, contiguous, because LovyanGFX's GFXfont::getGlyph indexes
`glyph[c - first]` with uint16_t bounds. The unused 0x7F-0xBF block costs 7
bytes of glyph table each and no bitmap, which is cheaper than the range-table
machinery it would take to skip them.

Source font is DejaVu Sans (Bitstream Vera license — redistributable, unlike
anything in /System/Library/Fonts), taken from the local matplotlib install so
this script does not download anything.

    python3 tools/make_font.py

Regenerate and commit the output when you change the size; the firmware build
does not run this.
"""
import os
import sys

FIRST, LAST = 0x20, 0xFF
SIZE = 13                      # px; yields ~17 px line height, close to Font2's 16
NAME = "FontLatin"
OUT = os.path.join(os.path.dirname(__file__), "..", "firmware",
                   "components", "expressions", "font_latin.h")


def find_dejavu():
    try:
        import matplotlib
        p = os.path.join(matplotlib.get_data_path(), "fonts", "ttf", "DejaVuSans.ttf")
        if os.path.exists(p):
            return p
    except ImportError:
        pass
    for p in ("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
              "/usr/share/fonts/TTF/DejaVuSans.ttf"):
        if os.path.exists(p):
            return p
    sys.exit("DejaVuSans.ttf not found (pip install matplotlib, or install fonts-dejavu)")


def main():
    from PIL import Image, ImageDraw, ImageFont

    ttf = find_dejavu()
    font = ImageFont.truetype(ttf, SIZE)
    ascent, descent = font.getmetrics()
    y_advance = ascent + descent

    pad = SIZE * 3
    canvas = (SIZE * 6, SIZE * 6)

    bitmap = bytearray()
    glyphs = []
    for cp in range(FIRST, LAST + 1):
        ch = chr(cp)
        img = Image.new("L", canvas, 0)
        # anchor="ls": the origin is the pen position on the baseline, which is
        # exactly the reference point Adafruit's xOffset/yOffset are measured
        # from. Getting this wrong tilts every accent by a pixel.
        ImageDraw.Draw(img).text((pad, pad), ch, font=font, fill=255, anchor="ls")
        box = img.point(lambda v: 255 if v >= 128 else 0).getbbox()
        advance = round(font.getlength(ch))

        # 0x7F-0x9F are control codes. DejaVu draws .notdef boxes for them,
        # which is the exact artefact this font exists to remove, so blank them.
        if 0x7F <= cp <= 0x9F:
            box, advance = None, 0

        if box is None:                       # space, and anything unrenderable
            glyphs.append((len(bitmap), 0, 0, advance, 0, 0))
            continue

        x0, y0, x1, y1 = box
        w, h = x1 - x0, y1 - y0
        px = img.load()
        offset, acc, nbits = len(bitmap), 0, 0
        for y in range(y0, y1):               # continuous MSB-first bitstream,
            for x in range(x0, x1):           # no per-row padding
                acc = (acc << 1) | (1 if px[x, y] >= 128 else 0)
                nbits += 1
                if nbits == 8:
                    bitmap.append(acc)
                    acc, nbits = 0, 0
        if nbits:
            bitmap.append(acc << (8 - nbits))
        glyphs.append((offset, w, h, advance, x0 - pad, y0 - pad))

    with open(os.path.abspath(OUT), "w") as f:
        f.write(f"""// GENERATED by tools/make_font.py -- do not edit by hand.
//
// {NAME}: DejaVu Sans {SIZE}px, codepoints 0x{FIRST:02X}-0x{LAST:02X}.
// Exists because every font LovyanGFX ships stops at 0x7E/0x7F, so accented
// characters rendered as boxes. Latin-1 covers everything Spanish needs:
// a-acute through u-diaeresis, n-tilde, and the inverted marks at 0xA1/0xBF.
//
// DejaVu Sans is under the Bitstream Vera Fonts Copyright (permissive, allows
// redistribution). See https://dejavu-fonts.github.io/License.html
#pragma once
#include <cstdint>
#include "lgfx/v1/lgfx_fonts.hpp"

namespace buddy {{

static constexpr uint8_t {NAME}Bitmaps[] = {{
""")
        for i in range(0, len(bitmap), 16):
            f.write("  " + " ".join(f"0x{b:02X}," for b in bitmap[i:i + 16]) + "\n")
        f.write("};\n\nstatic constexpr lgfx::GFXglyph " + NAME + "Glyphs[] = {\n")
        for cp, g in zip(range(FIRST, LAST + 1), glyphs):
            o, w, h, a, dx, dy = g
            # Quote it: codepoint 0x5C is a backslash, and a comment ending in
            # one splices the next line into it. The build is -Werror.
            ch = f"'{chr(cp)}'" if 0x20 < cp < 0x7F else ""
            note = f"  // 0x{cp:02X} {ch}".rstrip()
            f.write(f"  {{{o:6}, {w:3}, {h:3}, {a:3}, {dx:4}, {dy:4}}},{note}\n")
        f.write(f"""}};

static constexpr lgfx::GFXfont {NAME} = {{
  (uint8_t*)  {NAME}Bitmaps,
  (lgfx::GFXglyph*) {NAME}Glyphs,
  0x{FIRST:02X}, 0x{LAST:02X}, {y_advance}
}};

}}  // namespace buddy
""")

    drawn = sum(1 for g in glyphs if g[1])
    # GFXglyph is uint32 + 3x uint8 + 2x int8 = 9 bytes, padded to 12 by the
    # uint32's alignment. Verified against nm on the built ELF.
    table = len(glyphs) * 12
    print(f"{NAME}: {LAST - FIRST + 1} codepoints ({drawn} with ink), "
          f"{len(bitmap)} B bitmap + {table} B table = {len(bitmap) + table} B, "
          f"line height {y_advance}px -> {os.path.normpath(OUT)}")


if __name__ == "__main__":
    main()
